conf = {
    # "save_path": "E:/NSM/trained0924",
    "save_path": "/media/fish/data/NSM/trained",
    "load_path": "/media/fish/data/NSM/trained",
    "CUDA_VISIBLE_DEVICES": "2",
    "data": {
        # 'dataset_path':"E:/NSM/data1",
        'dataset_path': "/media/fish/data/NSM/data1",
    },
    "model": {
        'model_name': 'NSM',
        'epoch': 150,
        'batch_size': 64,
        'segmentation': [0, 419, 575, 2609, 4657, 5307],
        'encoder_nums': 4,
        'encoder_dims': [[419, 512, 512],
                         [156, 128, 128],
                         [2034, 512, 512],
                         [2048, 512, 512]],
        'encoder_activations': [['elu', 'elu'],
                                ['elu', 'elu'],
                                ['elu', 'elu'],
                                ['elu', 'elu']],
        'encoder_dropout': 0.3,
        'expert_components': [1, 10],
        'expert_dims': [[650, 512, 512, 10],
                        [1664, 512, 512, 618]],
        'expert_activations': [['elu', 'elu', 'softmax'],
                               ['elu', 'elu', None]],
        'expert_dropout': 0.3,
        'lr': 0.0001,
    },
}
